# Generated by Django 4.0.4 on 2022-05-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myLmsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('login', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.IntegerField()),
                ('problem_id', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('problem_code', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=25)),
                ('solved_number', models.IntegerField()),
                ('total_grade', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
