# Generated by Django 4.0.4 on 2022-06-17 14:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myLmsApp', '0003_remove_problem_input_remove_problem_output_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grades',
            new_name='Grade',
        ),
        migrations.AlterModelTable(
            name='chat',
            table='table2',
        ),
    ]
