# Generated by Django 4.0.4 on 2022-06-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myLmsApp', '0004_rename_grades_grade_alter_chat_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
