# Generated by Django 4.0.4 on 2022-06-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myLmsApp', '0005_problem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='m_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='problemio',
            name='input',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problemio',
            name='output',
            field=models.TextField(),
        ),
    ]
