# Generated by Django 4.0.4 on 2022-06-29 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myLmsApp', '0006_alter_module_m_description_alter_problem_description_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chat',
            table=None,
        ),
    ]
